version: '3.8'

services:
  # 자율주행차 서비스 이름
  picar:
    # 현재 디렉토리의 Dockerfile을 사용하여 이미지 빌드
    build: .
    # 이미지 이름 지정
    image: rasp5-app:latest
    # 컨테이너 이름
    container_name: picar-runner
    # 항상 재시작
    restart: always
    # 호스트의 네트워크를 그대로 사용 (매우 편리함)
    network_mode: "host"
    # 장치 접근 권한
    privileged: true
    # 볼륨 마운트 (공유 폴더 등)
    volumes:
      - /dev:/dev
      - ./shared_data:/home/ubuntu/shared  # 예시: 데이터를 공유할 폴더
    # 환경 변수
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
