# 파일 경로: .github/workflows/ci.yml
name: CI - Lint, Build, Test and Create Artifact

on:
  push:
    branches: [ sh-dev ]
  pull_request:
    branches: [ main ]

jobs:
  quality_check_and_build:
    name: Code Quality Check and Build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lint, Build, and Test inside CI Container
        run: |
          docker exec ci-runner /bin/bash -c " \
            set -e && \
            cd /ros2_ws && \
            cp -r /__w/rasp5/rasp5/src/. ./src/ && \
            source /opt/ros/humble/setup.bash && \
            rosdep install --from-paths src --ignore-src -r -y --rosdistro humble && \
            colcon lint --packages-select rasp5 && \
            colcon build --symlink-install --packages-up-to rasp5 && \
            colcon test --packages-select rasp5 && \
            colcon test-result --verbose \
          "

      - name: Copy build results from CI Container
        run: |
          mkdir -p ./artifact_payload
          docker cp ci-runner:/ros2_ws/install ./artifact_payload/install
          docker cp ci-runner:/ros2_ws/src ./artifact_payload/src

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ros2-build-artifact
          path: ./artifact_payload/
          retention-days: 7
