name: Autonomous Car CI

on:
  push:
    branches: [ sh-dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # ROS2 Humble은 Ubuntu 22.04를 권장합니다.
    runs-on: ubuntu-22.04
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ROS2 Humble 환경 설정 (가장 중요한 부분)
      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      # 3. 파이썬 의존성 설치
      - name: Install dependencies
        # ROS 환경을 불러온 후 pip를 실행해야 합니다.
        run: |
          source /opt/ros/humble/setup.bash
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

   # ...
      # 4. Pylint로 코드 린팅
      - name: Lint with Pylint
        run: |
          source /opt/ros/humble/setup.bash
          # 검사 대상을 src 디렉토리로 한정
          pylint --rcfile=.pylintrc src

      # 5. Pytest로 단위 테스트 실행 (나중에 추가 가능)
      # - name: Run Unit Tests
      #   run: |
      #     source /opt/ros/humble/setup.bash
      #     pytest tests/
