name: Autonomous Car CI

# 워크플로우 트리거 조건
on:
  push:
    branches: [ sh-dev ] # sh-dev 브랜치에 push될 때
  pull_request:
    branches: [ main ] # main 브랜치로 PR이 생성될 때

jobs:
  # CI 작업을 정의
  build-and-test:
    runs-on: ubuntu-latest # 실행 환경
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # ROS2 Humble은 Python 3.10을 사용

      # 3. 파이썬 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Pylint로 코드 린팅
      - name: Lint with Pylint
        run: |
          pylint $(git ls-files '*.py') --rcfile=.pylintrc

      # 5. Pytest로 단위 테스트 실행
      # - name: Run Unit Tests
      #   run: |
      #     pytest tests/
