# 워크플로우의 이름
name: Autonomous Car CI

# 워크플로우를 트리거하는 이벤트 설정
on:
  push:
    branches: [ sh-dev ]
  pull_request:
    branches: [ main ]

# 실행될 작업(job) 목록
jobs:
  # "build-and-test" 라는 이름의 작업
  build-and-test:
    # 이 작업이 실행될 가상 머신 환경 (Ubuntu 22.04 LTS)
    runs-on: ubuntu-22.04

    # 작업 내에서 실행될 단계(step) 목록
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ROS 2 설치 디렉토리 캐싱
      - name: Cache ROS 2 installation
        id: cache-ros
        uses: actions/cache@v3
        with:
          path: /opt/ros/humble
          key: ${{ runner.os }}-ros-humble-v1

      # 3. ROS 2 설치 (캐시가 없을 경우에만 실행)
      - name: Set up ROS 2
        if: steps.cache-ros.outputs.cache-hit != 'true'
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      # 4. Pip 패키지 캐싱
      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 5. 파이썬 의존성 패키지 설치
      - name: Install dependencies
        run: |
          source /opt/ros/humble/setup.bash
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      # 6. Pylint로 코드 린팅하고 결과를 파일로 저장
      - name: Lint with Pylint and Generate Report
        run: |
          source /opt/ros/humble/setup.bash
          mkdir -p reports
          pylint --rcfile=.pylintrc src | tee reports/pylint_report.txt || true

      # 7. 린트 결과 보고서를 Artifact로 업로드
      - name: Upload Pylint Report
        uses: actions/upload-artifact@v4 # <--- 이 부분이 v3에서 v4로 변경되었습니다!
        with:
          name: pylint-report
          path: reports/
