# 워크플로우의 이름
name: Autonomous Car CI

# 워크플로우를 트리거하는 이벤트 설정
on:
  push:
    branches: [ sh-dev ]
  pull_request:
    branches: [ main ]

# 실행될 작업(job) 목록
jobs:
  # ==========================================================
  # 작업 1: 코드 정적 분석 (린트) 및 보고서 생성
  # ==========================================================
  lint-and-report:
    runs-on: ubuntu-latest
    # ★ 이 작업 전체를 ROS2 개발 도구가 설치된 Docker 컨테이너 안에서 실행
    container:
      image: ros:humble-ros-dev-llm-1
    
    steps:
      # 1-1. 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1-2. 파이썬 의존성 패키지 설치
      - name: Install dependencies
        run: pip3 install -r requirements.txt

      # 1-3. Pylint로 코드 린팅하고 결과를 파일로 저장 (실패해도 중단 안 함)
      - name: Lint with Pylint and Generate Report
        run: |
          mkdir -p reports
          pylint --rcfile=.pylintrc src | tee reports/pylint_report.txt || true

      # 1-4. 린트 결과 보고서를 Artifact로 업로드
      - name: Upload Pylint Report
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: reports/

  # ==========================================================
  # 작업 2: 빌드, 단위 테스트, 통합 테스트 실행
  # ==========================================================
  build-and-test:
    # 'lint-and-report' 작업이 끝나야만 이 작업이 실행됨
    needs: lint-and-report
    runs-on: ubuntu-latest
    # ★ 이 작업 역시 동일한 Docker 컨테이너 안에서 실행
    container:
      image: ros:humble-ros-dev-llm-1

    steps:
      # 2-1. 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2-2. 파이썬 의존성 패키지 설치
      - name: Install dependencies
        run: pip3 install -r requirements.txt

      # 2-3. ROS2 패키지 빌드 (★ 여기서 실패하면 워크플로우 실패)
      - name: Build the ROS 2 package
        run: colcon build --packages-select picar_pkg
          
      # 2-4. 단위 테스트 실행 (★ 여기서 실패하면 워크플로우 실패)
      - name: Run Unit Tests with Pytest
        run: |
          source install/setup.bash
          pytest tests/

      # 2-5. 통합 테스트용 스크립트 실행 (★ 여기서 실패하면 워크플로우 실패)
      - name: Run the Integration Test script
        run: |
          source install/setup.bash
          ros2 run picar_pkg test_runner --ros-args -l INFO
