# 워크플로우의 이름
name: Autonomous Car CI

# 워크플로우를 트리거하는 이벤트 설정
on:
  push:
    branches: [ sh-dev ]
  pull_request:
    branches: [ main ]

jobs:
  # ==========================================================
  # 작업 1: 코드 정적 분석 (린트) 및 보고서 생성
  # ==========================================================
  lint-and-report:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Lint with Pylint and Generate Report
        run: |
          mkdir -p reports
          pylint --rcfile=.pylintrc src/picar_pkg | tee reports/pylint_report.txt || true
      - name: Upload Pylint Report
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: reports/

  # ==========================================================
  # 작업 2: 빌드, 단위 테스트, 통합 테스트 실행
  # ==========================================================
  build-and-test:
    needs: lint-and-report
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: src/picar_pkg
      - name: Cache ROS 2 installation
        id: cache-ros
        uses: actions/cache@v4
        with:
          path: /opt/ros/humble
          key: ${{ runner.os }}-ros-humble-v1
      - name: Set up ROS 2
        # 캐시가 없을 때만 ROS 2의 아주 기본적인 부분만 설치합니다.
        if: steps.cache-ros.outputs.cache-hit != 'true'
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      # ▼▼▼▼▼ 바로 이 부분이 근본적인 해결책입니다. ▼▼▼▼▼
      - name: Install ROS 2 base packages and dependencies
        run: |
          # 1. ROS 2 apt 저장소 설정 (이것은 여전히 필요합니다)
          sudo apt-get update
          sudo apt-get install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update

          # 2. [핵심] rosdep 대신, ROS 2 핵심 패키지 묶음(meta-package)을 직접 설치합니다.
          # ros-humble-ros-base는 ament_python을 포함한 모든 필수 라이브러리를 가지고 있습니다.
          sudo apt-get install -y ros-humble-ros-base

          # 3. (선택 사항) 만약 ROS2 패키지가 아닌 순수 Python 의존성이 있다면 설치합니다.
          # pip3 install -r requirements.txt
      # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

      - name: Build the ROS 2 package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --packages-select picar_pkg

      - name: Run Unit Tests with Pytest
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          pytest tests/

      - name: Run the Integration Test script
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
