# 파일 경로: .github/workflows/pipeline.yml

name: Main CI/CD Pipeline
on:
  push: { branches: [ sh-dev, main ] }
  pull_request: { branches: [ main ] }

jobs:
  build_and_test:
    name: 1. Build, Test & Create Artifact
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Lint, Build, and Test using Volume Mount
        run: |
          # ★★★ 여기가 핵심! 우리가 새로 만들 'rasp5-ci:humble' 이미지를 사용합니다. ★★★
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/ros2_ws" \
            rasp5-ci:humble /bin/bash -c " \
              set -e && \
              source /opt/ros/humble/setup.bash && \
              cd /ros2_ws && \
              rosdep install --from-paths src --ignore-src -r -y --rosdistro humble && \
              colcon lint --packages-select rasp5 && \
              colcon build --symlink-install --packages-up-to rasp5 && \
              colcon test --packages-select rasp5 && \
              colcon test-result --verbose \
            "
      - name: Upload Source Code as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code-artifact
          path: .

  deploy:
    name: 2. Deploy to Picar
    runs-on: self-hosted
    needs: build_and_test
    if: success()
    steps:
      - name: Download Source Artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code-artifact
      - name: Install Source Code and Build on Robot
        run: |
          rsync -a --delete ./ /home/car/rasp5/ && \
          cd /home/car/rasp5 && \
          source /opt/ros/humble/setup.bash && \
          colcon build --symlink-install
      - name: Restart ROS2 Service
        run: sudo systemctl restart picar_ros2.service
