# 1. 러너 프로그램을 설치할 폴더를 만들고, 그 안으로 이동합니다.
#    (홈 디렉토리에 만드는 것이 일반적입니다.)
mkdir ~/actions-runner && cd ~/actions-runner

# 2. 러너 프로그램 압축 파일을 다운로드합니다.
#    (아래 명령어는 GitHub 페이지에 있는 것을 그대로 복사해서 쓰세요. 버전이 다를 수 있습니다.)
curl -o actions-runner-linux-arm64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-arm64-2.317.0.tar.gz

# 3. (선택사항) 다운로드된 파일이 깨지지 않았는지 확인합니다.
#    GitHub 페이지에 있는 checksum 값과 비교해보세요.
# echo "YOUR_CHECKSUM actions-runner-linux-arm64-2.317.0.tar.gz" | shasum -a 256 -c

# 4. 압축을 풉니다.
tar xzf ./actions-runner-linux-arm64-*.tar.gz

# 5. [가장 중요!] 러너를 설정합니다.
#    아래 명령어는 GitHub 페이지에 있는 것을 **그대로 복사**해서 사용해야 합니다.
#    맨 뒤의 --token 값은 여러분의 저장소에만 부여된 고유한 비밀번호입니다.
./config.sh --url https://github.com/nachalsa/rasp5 --token YOUR_UNIQUE_TOKEN

#    이 명령어를 실행하면, 몇 가지 질문을 합니다.
#    - "Enter the name of runner group to add this runner to": 그냥 엔터 (기본 그룹)
#    - "Enter the name of runner": 그냥 엔터 (로봇 이름인 'picar'가 기본값)
#    - "Enter any additional labels": 그냥 엔터
#    - "Enter name of work folder": 그냥 엔터 ('_work'가 기본값)

#    모든 설정이 끝나면 "Settings Saved." 라는 메시지가 나옵니다.
