name: ROS2 CI on Picar Robot (Docker)

on:
  push:
    branches: [ sh-dev ]
  pull_request:
    branches: [ sh-dev ]

jobs:
  build-and-test-on-picar-docker:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Test inside 'humble' Container
        run: |
          echo "--- Starting build inside 'humble' container on Picar Robot ---"
          
          # --- 이 부분이 새로 추가됩니다! ---
          echo "--- Creating workspace directory inside container ---"
          # -p 옵션은 /ros2_ws/src 경로에 필요한 모든 상위 폴더를 한 번에 만들어줍니다.
          docker exec humble /bin/bash -c "mkdir -p /ros2_ws/src"
          
          # --- 여기서부터는 이전과 동일합니다 ---
          echo "--- Copying source code to container ---"
          docker cp $GITHUB_WORKSPACE/src/. humble:/ros2_ws/src
          
          echo "--- Executing build/test commands inside container ---"
          docker exec humble /bin/bash -c " \
            set -e && \
            source /opt/ros/humble/setup.bash && \
            cd /ros2_ws && \
            echo '--- Installing ROS dependencies (rosdep) ---' && \
            rosdep install --from-paths src --ignore-src -r -y && \
            echo '--- Building workspace (colcon build) ---' && \
            colcon build --symlink-install && \
            echo '--- Running tests (colcon test) ---' && \
            colcon test \
          "
