name: ROS2 CI on Picar Robot

on:
  # 1. 다음 브랜치들에 코드가 push 될 때 실행
  push:
    branches:
      - main
      - sh-dev
  
  # 2. 다음 브랜치들을 대상으로 Pull Request가 생성/업데이트 될 때 실행
  pull_request:
    branches:
      - main
      - sh-dev

jobs:
  build-and-test-on-picar:
    # 이 작업은 GitHub이 아닌, 우리가 등록한 'self-hosted' 러너에서 실행됩니다.
    runs-on: self-hosted

    steps:
      # 1단계: GitHub 저장소의 코드를 러너(picar 로봇)의 작업 폴더로 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2단계: 실제 로봇 환경에서 빌드와 테스트를 실행합니다.
      - name: Build and Test in Native Environment
        # 로봇은 이미 ROS2 환경이므로, 바로 colcon 명령어를 실행합니다.
        run: |
          echo "--- Starting build on Picar Robot ---"
          # 로봇 자체의 셸을 사용하므로, ROS 환경을 source 해줘야 합니다.
          source /opt/ros/humble/setup.bash
          # $GITHUB_WORKSPACE는 러너가 코드를 받아온 폴더입니다.
          echo "--- Moving to workspace: $GITHUB_WORKSPACE ---"
          cd $GITHUB_WORKSPACE
          echo "--- Installing dependencies (rosdep) ---"
          rosdep install --from-paths src --ignore-src -r -y
          echo "--- Building workspace (colcon build) ---"
          colcon build
          echo "--- Running tests (colcon test) ---"
          colcon test
