# .github/workflows/ci.yml
name: CI - Quality Check (for sh-dev)

# 언제 실행? -> sh-dev 브랜치에 코드가 push 되거나, main으로 Pull Request를 보낼 때
on:
  push:
    branches: [ sh-dev ]
  pull_request:
    branches: [ main ]

jobs:
  quality_check_and_build:
    name: Code Quality Check and Build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lint, Build, and Test inside Docker
        run: |
          docker exec humble /bin/bash -c " \
            set -e && \
            source /opt/ros/humble/setup.bash && \
            cd /ros2_ws && \
            rosdep install --from-paths src --ignore-src -r -y --rosdistro humble && \
            colcon lint --packages-select rasp5 && \
            colcon build --symlink-install --packages-up-to rasp5 && \
            colcon test --packages-select rasp5 && \
            colcon test-result --verbose \
          "

      - name: Copy build results for artifact
        run: |
          mkdir -p ./artifact_payload
          docker cp humble:/ros2_ws/install ./artifact_payload/install
          docker cp humble:/ros2_ws/src ./artifact_payload/src

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: ros2-build-artifact
          path: ./artifact_payload/
          retention-days: 7
